services:
  frontend: # this is really just nginx reverse proxy
    build:
      context: ./frontend
    ports:
      - "8003:80"

  backend:
    build:
      context: ./backend
    ports:
      - "8004:8080"
    depends_on:
      - db

  db:
    image: postgres
    restart: no
    shm_size: 128mb
    volumes:
      - postgres-data:/var/lib/postgres/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    secrets:
      - pgpass

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "name@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin-data:
    
secrets:
  pgpass:
    file: .pgpass
  root_password:
    file: db_root_password.txt