services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - client-side
    ports:
      - "8003:80"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - client-side
      - server-side
    ports:
      - "8004:8080"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    networks:
      - server-side
    volumes:
      - postgres-data:/var/lib/postgres/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "name@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - db
  
networks:
  client-side: {}
  server-side: {}

volumes:
  postgres-data:
    
secrets:
  db_password:
    file: db_password.txt
  